### ISSUE TITLE
small disagreement in doc

### ISSUE THREAD

**Issue by ZuBB** [Platypi/style_typescript#1]
> Each line should contain at most one statement.

good

> A semicolon should be placed at the end of every simple statement.

very good

> ```
> let a = 2,
>     b = 4;
> ```

:collision:

**Comment by ZuBB** [comment]
ps: do not take it too seriously :wink:

**Comment by wjohnsto** [comment]
Good catch, it would seem that I contradict myself! In general though with regards to the second part you mentioned, as long as you maintain consistency it doesn't really matter if you use:

``` typescript
let a = 2;
let b = 4;
```

or

``` typescript
let a = 2,
    b = 4;
```
