### ISSUE TITLE
style doc recommends to use lib that is deprecated

### ISSUE THREAD

**Issue by ZuBB** [Platypi/style_typescript#2]
in your doc

> Use tsd for all external library declarations

in tsd's doc

> DEPRECATED: TSD is deprecated, please use Typings and see this issue for more information.

https://github.com/DefinitelyTyped/tsd/issues/269

**Comment by wjohnsto** [comment]
You are correct! I will update this.

**Comment by wjohnsto** [comment]
This is now fixed
