### ISSUE TITLE
Is it really an IDE when it cannot handle tabs?

### ISSUE THREAD

**Issue by robertomulabi** [Platypi/style_typescript#3]
> Never use tabs, as this can lead to trouble when opening files in different IDEs/Text editors. Most text editors have a configuration option to change tabs to spaces.

Entirely out of curiosity: what **IDE**s have trouble when opening files with tabs?
Even notepad seems to be able to handle tabs properly.  :smile:

**Comment by wjohnsto** [comment]
I suppose that could be rephrased to say something along the lines of "Tabs can take up any number of columns depending upon your environment, where a space is always one column." That being said, it's more important to be consistent than anything, so whatever you/your team want to use make sure you are all using the same method.
